#!/bin/bash

set -euo pipefail

# Set shell to zsh
if command -v zsh >/dev/null; then
    sudo chsh -s $(command -v zsh) $USER
fi

# Install plugins if Oh My Zsh is installed
if [ -d "$HOME/.oh-my-zsh" ]; then
  ZSH="${ZSH:-$HOME/.oh-my-zsh}"
  ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"
  mkdir -p "$ZSH_CUSTOM/plugins"

  [ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] || \
    git clone https://github.com/zsh-users/zsh-autosuggestions.git "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
  [ -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ] || \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
  [ -d "$ZSH_CUSTOM/plugins/zsh-autocomplete" ] || \
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git "$ZSH_CUSTOM/plugins/zsh-autocomplete"
fi

# Install Starship if missing
if ! command -v starship >/dev/null 2>&1; then
  curl -fsSL https://starship.rs/install.sh | sh -s -- --yes
fi

# Install chezmoi and apply dotfiles
if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:markoonakic/dotfiles.git
fi

# Clone neovim configuration
NVIM_DIR="$HOME/.config/nvim"
REPO="git@github.com:markoonakic/funky-nvim.git"
mkdir -p "$(dirname "$NVIM_DIR")"
[ -d "$NVIM_DIR/.git" ] || git clone --depth 1 "$REPO" "$NVIM_DIR"

exit 0
