#!/bin/bash

set -euo pipefail

# Set shell to zsh
if command -v zsh >/dev/null; then
    sudo chsh -s $(command -v zsh) $USER
fi

# Install Starship if missing
if ! command -v starship >/dev/null 2>&1; then
  curl -fsSL https://starship.rs/install.sh | bash -s -- --yes
fi

# Install chezmoi and apply dotfiles
if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:markoonakic/dotfiles.git
fi

exit 0
